[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update && apt-get install --assume-yes libudev-dev:armhf libinput-dev:armhf libdrm-dev:armhf",
]
