[target.armv7-unknown-linux-musleabihf]
pre-build = [
    "apt-get update && apt-get install -y libudev-dev libinput-dev libdrm-dev libgl1-mesa-dev libxkbcommon-dev fonts-dejavu fontconfig",
    "fc-cache -fv",
]
